# Generated by Django 4.1.7 on 2023-09-01 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0002_alter_user_phone_alter_user_pincode"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="ContentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("body", models.CharField(max_length=300)),
                ("summary", models.CharField(max_length=60)),
                ("pdf", models.ImageField(upload_to="pdf")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Author",
                        to="cms.user",
                    ),
                ),
                ("categories", models.ManyToManyField(to="cms.category")),
            ],
            options={
                "db_table": "ContentItem",
                "managed": True,
            },
        ),
    ]
