# Generated by Django 4.1.7 on 2023-09-01 03:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0003_category_contentitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contentitem",
            name="categories",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
